
version: '3.8'
services:
  backend:
    build: ./backend
    command: npm run start
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
  frontend:
    build: ./frontend
    command: npm run preview -- --host 0.0.0.0 --port 5173
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
